### ISSUE TITLE
What should be added to mirthConfig.json to specify MirthEngine port if different than 8443

### ISSUE THREAD

**Issue by iacsha** [feathersct/mirth-prometheus-exporter#1]
I attempted to set 
` "instance": "localhost:18443"`

received `requests.exceptions.InvalidURL: Failed to parse: https://localhost:18443:8443/api/users/_logout`

What can I put into the JSON to use port other than 8443?

**Comment by dloial** [comment]
hi
I have exactly the same issue. 
8443 is appended to my URL no matter what I try

**Comment by feathersct** [comment]
@iachettashawn and @dloial good catch. MirthPy allows for a port to be specified but the exporter doesn't allow you to specify. I will get an update shortly for you to add a port.

**Comment by dloial** [comment]
I worked around this issue by modifying the port in /usr/local/lib/python3.9/site-packages/mirthpy/mirthService.py

**Comment by dloial** [comment]
Hi I have an issue when trying to launch python.
it appends  /api/users/_logout after the mirth url and it causes it to fail with the following error:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //172.17.160.32:8587/api/users/_logout (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1d94442af0>: Failed to establish a new connection: [Errno -2] Name or service not known'))


Is it an expected behavior ?

**Comment by feathersct** [comment]
@iachettashawn and @dloial the [latest push](https://github.com/feathersct/mirth-prometheus-exporter/commit/54718a89c8b697c7114f9b966ace1f87d4c8fbea) will fix this issue. Let me know if you still see an issue.
